[package]
name = "dash-mpd-cli"
version = "0.1.14"
authors = ["Eric Marsden <eric.marsden@risk-engineering.org>"]
license = "MIT"
description = "Download content from a DASH-MPEG or DASH-WebM MPD manifest"
readme = "README.md"
repository = "https://github.com/emarsden/dash-mpd-cli"
keywords = ["video", "streaming", "DASH", "MPEG", "download"]
categories = ["command-line-utilities", "multimedia", "multimedia::video"]
edition = "2021"
publish = true


[dependencies]
tokio = { version = ">=1.24.2", features = ["rt-multi-thread", "macros"] }
dash-mpd = { version = ">=0.9.2", default-features = false, features = ["fetch", "compression", "rustls-tls", "scte35"] }
reqwest = { version = "0.11", default-features = false, features = ["gzip", "brotli", "rustls-tls", "socks"] }
strum = "0.24"
colored = "2"
indicatif = "0.17"
clap = { version = "4", features = ["cargo", "unicode"] }
fs-err = "2.9"
number_prefix = "0.4"
anyhow = "1"
log = "0.4"
env_logger = "0.10"
bench_scraper = { version = "0.4", features = ["reqwest"], optional = true }

[dev-dependencies]
rustls = "0.21"
rustls-pemfile = "1.0"
tokio = { version = ">=1.24.2", features = ["rt-multi-thread", "time", "macros"] }
axum = "0.6"
axum-server = { version = "0.5", features = ["tls-rustls"] }
quick-xml = "0.29"

[features]
default = ["cookies"]
cookies = ["bench_scraper"]


[profile.release]
opt-level = "z"  # optimize for size
lto = "fat"
codegen-units = 1
