# Build a Docker/Podman container with dash-mpd-cli and its external helper applications. We
# currently build for Linux/AMD64, Linux/aarch64, Linux/armv7 (32 bit) and Linux/riscv64.
#
# We Build for the different architectures in parallel, or we run into the 360 minute workflow
# timeout.

name: Build container images/parallel

on: workflow_dispatch

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  create-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Create Podman manifest
        run: podman manifest create dash-mpd-cli
    
  build-amd64:
    needs: create-manifest
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu
        run: sudo apt install qemu-user-static

      - name: Checkout sources
        uses: actions/checkout@v4

        # We use "buildah build" instead of "podman build", because we are seeing errors on the older
        # version of podman installed on the runners.
      - name: Build image/amd64
        run: buildah build -f etc/Containerfile_linux_amd64 --platform linux/amd64 --tag dash-mpd-cli-linux-amd64 --manifest dash-mpd-cli .

     
  build-aarch64:
    needs: create-manifest
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu
        run: sudo apt install qemu-user-static

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build image/aarch64
        run: buildah build -f etc/Containerfile_linux_aarch64 --platform linux/arm64 --tag dash-mpd-cli-linux-aarch64 --manifest dash-mpd-cli .

  build-armv7:
    needs: create-manifest
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu
        run: sudo apt install qemu-user-static

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build image/armv7
        run: buildah build -f etc/Containerfile_linux_armv7 --platform linux/arm/v7 --tag dash-mpd-cli-linux-armv7 --manifest dash-mpd-cli .

  build-riscv64:
    needs: create-manifest
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu
        run: sudo apt install qemu-user-static

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build image/riscv64
        run: buildah build -f etc/Containerfile_linux_riscv64 --platform linux/riscv64 --tag dash-mpd-cli-linux-riscv64 --manifest dash-mpd-cli .


  push-image:
    needs: [build-amd64, build-aarch64, build-armv7, build-riscv64]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    name: Build and push container/Linux
    steps:
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Push container image
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: dash-mpd-cli
          tags: latest
          registry: ${{ env.IMAGE_REGISTRY }}

