name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  publish:
    name: Publish release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: dash-mpd-cli
            asset_name: dash-mpd-cli-linux-amd64
          - os: windows-latest
            artifact_name: dash-mpd-cli.exe
            asset_name: dash-mpd-cli-windows-amd64
          - os: macos-latest
            artifact_name: dash-mpd-cli
            asset_name: dash-mpd-cli-macos-amd64

    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        install: base-devel autotools mingw-w64-x86_64-toolchain mingw-w64-x86_64-rust mingw-w64-ucrt-x86_64-gcc

    - name: Build
      shell: msys2 {0}
      run: cargo build --release

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
