# Run cargo tests in a Solaris VM. This needs to run on one of the GitHub macos runners, because
# they are currently the only ones to support virtualization.
#
# See https://github.com/vmactions/solaris-vm

on: [push]

name: solaris

jobs:
  test:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Run tests in Solaris VM
      uses: vmactions/solaris-vm@v0
      with:
        usesh: true
        prepare: |
          pkgutil -y -i curl
          curl https://sh.rustup.rs -sSf --output rustup.sh
          sh rustup.sh -y --profile minimal --default-toolchain stable
          export PATH="${HOME}/.cargo/bin:$PATH"
          echo "~~~~ rustc --version ~~~~"
          rustc --version

        run: |
          export PATH="${HOME}/.cargo/bin:$PATH"
          ls -la
          cargo build --verbose
          cargo test --verbose
