# Run cargo tests in a Solaris VM. This needs to run on one of the GitHub macos runners, because
# they are currently the only ones to support virtualization.
#
# A normal rustup install fails on Solaris 11.4 as of 2023-08, as does an attempt to install via the
# pkg tool, so this is currently disabled.
#
# See https://github.com/vmactions/solaris-vm

on: workflow_dispatch

name: solaris

jobs:
  test:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Run tests in Solaris VM
      uses: vmactions/solaris-vm@v0
      with:
        usesh: true
        prepare: |
          pkgutil -y -i curl
          pkg install developer/rust/rustc developer/rust/cargo
          echo "~~~~ rustc --version ~~~~"
          rustc --version

        run: |
          export PATH="${HOME}/.cargo/bin:$PATH"
          ls -la
          cargo build --no-default-features --verbose
          cargo test --no-default-features --verbose
